sudo: required
language: generic

services:
  - docker

stages:
  - build
  - publish

jobs:
  include:
    - stage: build
      name: "Build and check the image"
      script:
        - docker build -t crystal:latest .
        - docker run crystal:latest crystal -v
      if: branch = master

    - stage: publish
      name: "Publish the image to DockerHub"
      before_script:
        - echo "$DOCKERHUB_PASSW" | docker login -u caian --password-stdin
      script:
        - docker build -t "$DOCKER_IMG" .
        - docker push "$DOCKER_IMG"
        - docker tag "$DOCKER_IMG" "$DOCKER_LATEST"
        - docker push "$DOCKER_LATEST"
      env:
        - DOCKER_REPO="caian/crystal"
        - DOCKER_IMG="${DOCKER_REPO}:${TRAVIS_TAG}-alpine"
        - DOCKER_LATEST="${DOCKER_REPO}:latest"
      if: tag IS present
